### PR TITLE
Cleanup + space edit

### PR DESCRIPTION
**Pull request by Coder-256**
Cleaned up panel.js and maximized space for all GitHub pages. Works both with and without panel enabled.

### CODE REVIEW

**Comment by camsong** [comment]
Thanks so much, @Coder-256

**Comment by Anahkiasen** [comment]
Is there a way to disable it? On a 27" it makes pages _reaaaaally_ wide, kinda uncomfortable to use

**Comment by camsong** [comment]
@Anahkiasen sorry for that :crying_cat_face: , will release a fix shortly

**Comment by Anahkiasen** [comment]
Oh no worries, just disabled the extension for the moment, still an awesome extension in any case :+1:

**Comment by camsong** [comment]
Will not remove that awesome feature for sure, just removed `insertPanelCSS` function to use the original style by github. released v0.14.4.

Anyway, you can always disabled the `panel` feature as well as other feature by `octo-mate` if your want:

**Pull request merged**
